# Blowfish Theme Parameters

colorScheme = "custom"
defaultAppearance = "light"
autoSwitchAppearance = false

enableSearch = true
enableCodeCopy = true

mainSections = ["posts", "training"]
robots = ""

[header]
  layout = "fixed"
  logo = ""
  showTitle = true

[footer]
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "custom"
  showRecent = true
  recentLimit = 6

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showWordCount = false
  showComments = false
  sharingLinks = ["linkedin", "twitter", "email"]

[list]
  showBreadcrumbs = true
  showSummary = true
  showTableOfContents = false
  groupByYear = false

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true

[fathomAnalytics]
  site = ""

[verification]
  google = ""
  bing = ""
